add button component
fs-mar24-codemafia/react_gadgets-depot pull request #6
Opened 2024-06-05 08:38 UTC by AYupko

2024-06-05 18:39 UTC, lmmaarriiaa requested changes
Please make this button as a button tag and add onClick function that it will accept in props 
Its a button, not a link 
Thanks!

2024-06-05 23:07 UTC, AYupko commented
> Please make this button as a button tag and add onClick function that it will accept in props Its a button, not a link Thanks!

At the moment it`s just UI component without any logic. What`s the sense of adding function now. As soon as we have logic, we implement it here.

2024-06-06 11:32 UTC, lmmaarriiaa approved these changes

2024-06-06 11:33 UTC, TetianaVeremchuk approved these changes

2024-06-06 13:32 UTC, merged